### PR TITLE
Codec uses buffer pool with compilation flag

### LINKED ISSUE #103: use buffer pool

### PR DESCRIPTION
**Pull request by atalw**
This closes #103 and #96. 

I'm new to the codebase so I may have missed something. Please let me know. Thanks.

### CODE REVIEW

**Comment by Fi3** [comment]
Hi @atalw, thanks for the interest in Sv2.

codec-sv2 define the Buffer trait in codec-sv2/buffer.rs and implement it for the struct SlowAndCorrect also it in codec-sv2/buffer.rs

Btw it should use the Buffer trait defined in utils/buffer.

In utils/buffer we have 2 struct the implements the Buffer trait:
1. BufferFromSystemMemory in utils/buffer/buffer.rs
2. BufferPool in utils/buffer/buffer_pool

coedc-sv2 should have a compilation flag (cargo feature) to chose between the 2 Buffer implementation.
Without flag we should default to BufferFromSystemMemory that will replace SlowAndCorrect
With the flag codec-sv2 should use the faster BufferPool that will replace SlowAndCorrect

There is no need to change framing-sv2 signatures.

Let me know if you need anything else. If you want to chat about that you can participate to the weekly dev meeting.

**Comment by atalw** [comment]
Hey @Fi3, thanks for the explanation. Let me just make sure I understand it properly.

We want a compilation flag in Codec to toggle between the 2 Buffer implementations. With flag, we use `BufferPool` and without flag we use `BufferFromSystemMemory`.

And we don't need `codec-sv2/buffer.rs` anymore since we'll be using the Buffer implementations in `utils/buffer`. So I can remove it. Sounds good?

> There is no need to change framing-sv2 signatures.

I changed it because the compiler was throwing a `trait bounds not satisfied` error. But this was in the previous implementation. I'll remove it and check for the refactor.

> If you want to chat about that you can participate to the weekly dev meeting.

Is there a project Slack/discord I could join?

**Comment by Fi3** [comment]
@atalw  yes you understood it correctly.

Here the discord link: https://discord.gg/vsKy8A7E

**Comment by pavlenex** [comment]
Hey @atalw are you still interested in continuing to tackling this issue as per @Fi3 comments? We'd like to have it tackled in the next 2 weeks, as we wrap up our [milestone 0.01](https://github.com/stratum-mining/stratum/milestone/6). Let us know if you have time to commit, would be great, no harsh feeling if you can't.

**Comment by atalw** [comment]
Hey, unfortunately I'm in the middle of some work so I won't be able to pick this up soon. I'll close this PR and resubmit if I get around to doing it.

**Pull request closed without merging**
