### PR TITLE
Merge `protocols` and `roles` workspaces

### PR DESCRIPTION
**Pull request by jbesraa**
#1125 

This commits removes the `protocols` and `roles` workspaces and creates a new shared workspace for both of them. In practice we dont have a need to maintain two different workspaces and no benefit is derived from that.

With moving to a shared workspaces, the naming of the parent folders was changed as will with `roles` becoming `stratum-roles` and `protocols` becoming `stratum-protocols` and same for `common` crate. This required a fix a across the codebase of the imports inside the different `Cargo.toml`s.

### CODE REVIEW

**Comment by Fi3** [comment]
see my comment on related issue

**Comment by jbesraa** [comment]
@Fi3 I dont honestly remember when we talked about splitting them into different git repos, but anyhow thats a much bigger task than just combining them into a single workspace. Things are way over-engineered at the moment without any justification.

**Comment by plebhash** [comment]
> I think there is also an open issue about that by @plebhash ?

There is this proposal discussion for a repository split: https://github.com/stratum-mining/stratum/discussions/1069#discussioncomment-10290201

But I'm not in a rush to execute this split just yet, because this has many implications and needs to be properly planned. 

For now, I'd be happy to keep the discussion going on a conceptual level, so we get consensus on the best repository structure and we can eventually plan accordingly for the execution in the future.

> Btw we splitted the workspaces with the goal of putting protocols and roles in separate repos. The plan was somthing like that:
> 1. develop the low level libraries
> 2. develop  a bunch of roles with the intention of (1) test the library (2) show that sv2 could work
> 3. stabilize the libraries
> 4. use the libraries to develop a bunch o prod grade tools (proxies, translator, everything together) whatever we see that is more needed. (I would start with downstream tools since the pools can develop upstream tools for themself but ofc here I'm in confilct of interest :)

I think we are in the middle of 3 right now, via #845

And also #1120 will help bring more stability into the work that was done on 2, because we will be able to get more confidence that the roles implementations are correctly implementing the protocol spec.

Once we move into 4 in the future, we will basically be trying to bring the work that was done in 2 into production readiness. Which ones we will focus first is a future discussion, and hopefully by that time we will also have more feedback from industry adopters, which will help us make those decisions.

---

with regards to this actual PR, I'm not very opinionated

in case I come across something that makes me realize this is needed I'll come back here and elaborate, but for now I'll focus on other tasks

**Comment by Fi3** [comment]
concept nack
as the final goal is still to have different repos for libraries and applications

**Pull request closed without merging**
