### PR TITLE
impl: IdentifyTransactions.Success for jdc

### PR DESCRIPTION
**Pull request by marathon-gary**
We scrub the last declared mining jobs and collect a transaction list from the JD. Then mapping over the found transactions we convert the txid in the binary_sv2::U256 type. From this we can create a new Seq064K<U256> to send back from the JDC to the JDS that encountered a hash collision or was unable to recreate the tx_hash_list_hash.

Probably some code conciseness clean up I could do here but wanted to push the PR to gather feedback.

### CODE REVIEW

**Comment by plebhash** [comment]
I haven't dived into the code in detail, but a few points worth noting:

- #902 describes the fact that neither `IdentifyTransactions` nor `IdentifyTransactions.Success` are implemented. So it doesn't make sense to only implement `IdentifyTransactions.Success` in isolation.
- We need to assert the implementation of both messages for correctness, which can only be done via MG tests. [Here](https://www.youtube.com/watch?v=Gic7qrmWdU4&list=PL4okm1s0ZpT9YveJBiU51gaaOmNJviugi)'s a tutorial with some foundational knowledge on how to get started.
- Given that the PR is still WIP, it should be set as a Draft.

I don't think the `good-first-issue` was an accurate label and we probably made a mistake when we applied it to this task. Writing MG tests and making sure the implementation is sane is not necessarily trivial.

But I don't want to discourage you @marathon-gary , just letting you know that the challenge is probably bigger than originally perceived.

**Comment by marathon-gary** [comment]
Also Ack on both sides of the messaging not being implemented, I definitely misread the issue. Will keep working on this to learn the codebase.

**Comment by plebhash** [comment]
> Is there a good code example of the MG testing to reference? I'll look for some but referrals for starting points are always welcome.

Watch the youtube videos I embedded on my previous comment. It's the closest thing we have to some educational material on MG tests so far.

**Comment by rrybarczyk** [comment]
Closing until we address roles refactor after protocols refactor.

**Pull request closed without merging**
