### PR TITLE
Fix noise-handshake operations order

### PR DESCRIPTION
**Pull request by jakubtrnka**
This fixes issue #728

### CODE REVIEW

**Comment by jakubtrnka** [comment]
Unit tests for the correctness of each step should be added.

**Comment by Fi3** [comment]
@Sjors as soon as we have it on the TP we can merge

**Comment by Sjors** [comment]
A test case would indeed be very useful here, if only so that I can add it to the TP in Bitcoin Core and make sure the issue is fixed.

**Comment by Sjors** [comment]
Implemented the same on the Bitcoin Core side. Untested.
https://github.com/Sjors/bitcoin/pull/33

We should coordinate the merge timing for this.

**Comment by Sjors** [comment]
tACK 729cdecc0d3ae1bddeba9f118e436e5b3806da79

Tested against the Bitcoin Core branch.

**Pull request merged**
