### PR TITLE
workspace split

### PR DESCRIPTION
**Pull request by plebhash**
as discussed in https://github.com/stratum-mining/stratum/issues/702, this PR splits the project workspaces in terms of:
- `roles`
- `protocols`
- `utils`

`test`, `benches` and `examples` remain as standalone crates without being part of any workspace.

some notes:
- `experimental` was removed (see @Fi3 's comment https://github.com/stratum-mining/stratum/issues/702#issuecomment-1864022081)
- `vendored` is only used as a dependency by `jd-server`, so it was moved to `roles/jd-server`
- #702 also discusses a strategy for making `lib` available from `roles` crates... this will be done in a following PR

### CODE REVIEW

**Comment by GitGab19** [comment]
During yesterday's dev call, we agreed on the approach proposed here. 👏 
We will need a last review after failing test will be fixed @plebhash

**Comment by lorbax** [comment]
I am reviewing this PR

**Comment by lorbax** [comment]
I reviewed this PR and looks good to me.
I include the related issue, so that no one in the future can miss the discussion behind this PR
[https://github.com/stratum-mining/stratum/issues/702](url)

**Comment by Sjors** [comment]
This seems like a nice improvement. My only suggestion is to rebase onto the latest dev so that the merge commit cd806929e311bd2d939eab1a75c7c7f70403be14 disappears (and hopefully 17fa0427d63a35b85718b6b46735877a0d057a55 can be avoided).

**Review by GitGab19 — APPROVED** [review]

**Comment by plebhash** [comment]
> This seems like a nice improvement. My only suggestion is to rebase onto the latest dev so that the merge commit [cd80692](https://github.com/stratum-mining/stratum/commit/cd806929e311bd2d939eab1a75c7c7f70403be14) disappears (and hopefully [17fa042](https://github.com/stratum-mining/stratum/commit/17fa0427d63a35b85718b6b46735877a0d057a55) can be avoided).

done 👍

**Pull request merged**
