### PR TITLE
merge dev main

### PR DESCRIPTION
**Pull request by plebhash**
fix https://github.com/stratum-mining/stratum/issues/870

### CODE REVIEW

**Review by pavlenex — APPROVED** [review]

**Comment by lorbax** [comment]
The least commit shared between this branch and main is [this one](https://github.com/stratum-mining/stratum/commit/1611cdb84951d8cc8b27c655f3cd4530ab734161) which is not on top of main. Seems that this does not solve the issue

**Comment by plebhash** [comment]
> The least commit shared between this branch and main is [this one](https://github.com/stratum-mining/stratum/commit/1611cdb84951d8cc8b27c655f3cd4530ab734161) which is not on top of main. Seems that this does not solve the issue

@lorbax can you elaborate on what you see as a problem here?

these are the steps that led me to this PR:
```
git checkout dev
git checkout -b dev-merge-main
git merge origin main
# there was a confict on roles/Cargo.lock, which I solved by picking the state from `main`
git merge --continue
git push plebhash dev-merge-main
# opened PR
```

> tried to rebase manually commit by commit dev on main
this is the result
https://github.com/lorbax/stratum/tree/dev-rebased

I think manually rebasing every commit is too error prone. We should be able to fix this with a few commands.

**Comment by Fi3** [comment]
> # there was a confict on roles/Cargo.lock, which I solved by picking the state from `main`

If you are going to merge on dev you should take the state from dev not main

**Comment by lorbax** [comment]
I was wrong, the least common ancestor between this branch and main branch is the HEAD of main branch, so this PR solves the issue. It would have been better to rebase dev on main, so that we do not mess up with history of commits, which is what I tried to do in my branch (before you publish this PR)
[https://github.com/lorbax/stratum/tree/dev-rebased](https://github.com/lorbax/stratum/tree/dev-rebased)
Next time we should declare the issues we are working in!

**Comment by plebhash** [comment]
> > there was a confict on roles/Cargo.lock, which I solved by picking the state from `main`
> 
> If you are going to merge on dev you should take the state from dev not main
> 
> Considering that this PR do not change any code
> 
> This ofc assuming that lock on dev do not have any issue

`roles/Cargo.lock` is outdated on `dev`.

I noticed that because I use CLion and it automatically updates the lockfiles. So I got many conflicts on git because of that.

https://github.com/stratum-mining/stratum/commit/3ec6b50875e49dfed7415b0d99060302f437e467 updated this lockfile on `main`, and that was the motivation for picking the state of `main` on this merge conflict.

**Comment by Fi3** [comment]
> > > there was a confict on roles/Cargo.lock, which I solved by picking the state from `main`
> > 
> > 
> > If you are going to merge on dev you should take the state from dev not main
> > Considering that this PR do not change any code
> > This ofc assuming that lock on dev do not have any issue
> 
> `roles/Cargo.lock` is outdated on `dev`.
> 
> I noticed that because I use CLion and it automatically updates the lockfiles. So I got many conflicts on git because of that.
> 
> [3ec6b50](https://github.com/stratum-mining/stratum/commit/3ec6b50875e49dfed7415b0d99060302f437e467) updated this lockfile on `main`, and that was the motivation for picking the state of `main` on this merge conflict.

ok make sense

**Comment by plebhash** [comment]
> It would have been better to rebase dev on main, so that we do not mess up with history of commits, which is what I tried to do in my branch (before you publish this PR) https://github.com/lorbax/stratum/tree/dev-rebased 

https://github.com/stratum-mining/stratum/compare/dev...lorbax:stratum:dev-rebased

This diff shows 23 files being changed, where most of those changes were already introduced in PRs recently merged into `dev`. Is that expected? Git rebase is a bit confusing to me sometimes, that is why I went for a merge.

But if you prefer this approach we can replace this PR with another one from your branch, that would be no problem for me.

**Comment by lorbax** [comment]
> > It would have been better to rebase dev on main, so that we do not mess up with history of commits, which is what I tried to do in my branch (before you publish this PR) https://github.com/lorbax/stratum/tree/dev-rebased
> 
> [dev...lorbax:stratum:dev-rebased](https://github.com/stratum-mining/stratum/compare/dev...lorbax:stratum:dev-rebased)
> 
> This diff shows 23 files being changed, where most of those changes were already introduced in PRs recently merged into `dev`. Is that expected? Git rebase is a bit confusing to me sometimes, that is why I went for a merge.
> 
> But if you prefer this approach we can replace this PR with another one from your branch, that would be no problem for me.

For me it is fine whatever does work. There is not huge history that can possibly be messed up btw

**Comment by Fi3** [comment]
no you shouldn't get 23 diff files. IMO merging main on dev is ok.

**Pull request merged**
