### PR TITLE
Add missing doc comments for subprotocols messages

### PR DESCRIPTION
**Pull request by pythcoiner**
This PR:
- Add some docs/comments that were missing
- Try to unify the style used in these doc/comments
- Add formatting in order the ref to others structs or fields are well rendered by rust docs
- Fix some naming error about some referenced messages

### CODE REVIEW

**Review by jbesraa — COMMENTED** [review]
It would be much easier to review this if it was broken into smaller PRs. you are touching 4 different folder, so I think having a separate PR for each with detailed commits would make more sense

**Comment by pythcoiner** [comment]
> It would be much easier to review this if it was broken into smaller PRs. you are touching 4 different folder, so I think having a separate PR for each with detailed commits would make more sense

i can do this :+1:

**Comment by plebhash** [comment]
hey @pythcoiner thanks for this

it seems it's breaking `sv2_header_check` CI

**Comment by pythcoiner** [comment]
> hey @pythcoiner thanks for this
> 
> it seems it's breaking `sv2_header_check` CI

fixed

**Comment by rrybarczyk** [comment]
We need to split this PR up, one PR for each subcrate in `protocols::v2::subprotocols`.

**Pull request closed without merging**
