### PR TITLE
Add missing messages errors  constructors

### PR DESCRIPTION
**Pull request by pythcoiner**
This PR implement some missing messages errors 'constructor' in order to have all errors types from specs implemented.

### CODE REVIEW

**Comment by pythcoiner** [comment]
Btw, i don't really like the way i populate the `error_details` field, as this field is optionnal, shouldn't it have an Option<B064K> type? Or B064K should have `None` variant if length == 0? should `error_details` passed as argument?

**Review by jbesraa — COMMENTED** [review]
I see new functions added but are not used anywhere. what iam missing? 
could you please provide a link to the mentioned error types?

**Comment by pythcoiner** [comment]
> > I see new functions added but are not used anywhere. what iam missing? could you please provide a link to the mentioned error types?
> 
> I hold a similar view. Could you provide more context on the motivations behind this PR?

a part of the errors messages defined in the specs had 'constructors' implemented but not all, this PR try to add more consistency by implementing missing ones.

**Comment by jbesraa** [comment]
Yea but there is no point in adding functions that are not used. If we are not handling errors probably we should that, otherwise I dont see a point in pushing this code to dev

**Comment by rrybarczyk** [comment]
Closing, see [this comment](https://github.com/stratum-mining/stratum/pull/975#issuecomment-2200292376).

**Pull request closed without merging**
