### PR TITLE
update mining-device-sv1 to tracing

### PR DESCRIPTION
**Pull request by devworlds**
Hello, this is my first open-source pr, basically i follow what was asked.

- update mining-device-sv1 from println! to info! using tracing following mining-device as example.

- i don't update the eprintln! cause in the issue was mencioned only the println!

well, i hope this help.

the issue: https://github.com/stratum-mining/stratum/issues/1286

### CODE REVIEW

**Comment by plebhash** [comment]
rebasing with latest `main`

**Comment by plebhash** [comment]
the commit history is a bit messy

we do things, then we add extra commits to undo them out of regret of what we did in previous commits

the following commits shouldn't exist
- https://github.com/stratum-mining/stratum/pull/1294/commits/42610d96595284af7218bf178c470cc7dd480793
- https://github.com/stratum-mining/stratum/pull/1294/commits/b5ba8c13f0df604ed08506a25a8db51401843295
- https://github.com/stratum-mining/stratum/pull/1294/commits/e232fa5015a607939bab24bb3e4e10ffc2fb800a
- https://github.com/stratum-mining/stratum/pull/1294/commits/2cd6e4ca56391ea885b58cf3ded748f9854ca116

**Comment by plebhash** [comment]
commit https://github.com/stratum-mining/stratum/pull/1294/commits/060060225775a79a10eb23a2c848e4f72975f8de is weird because it's changing things on other crates (`jd_client` and `translator_sv2`)

this PR shouldn't need to touch any crate outside of `mining_device_sv1`... if we have to change anything on other crates, there's something wrong

**Comment by plebhash** [comment]
> i don't update the eprintln! cause in the issue was mencioned only the println!

apologies for the limited issue description

`eprintln!` should also be replaced

**Review by plebhash — CHANGES_REQUESTED** [review]
obrigado pela contribuicao @devworlds 🇧🇷

I left some comments on how we can proceed with this PR

**Comment by devworlds** [comment]
thanks for clarify, i will update the things!

**Comment by devworlds** [comment]
> > i don't update the eprintln! cause in the issue was mencioned only the println!
> 
> @devworlds apologies for the limited issue description, it's been fixed
> 
> `eprintln!` should also be replaced

sure!

**Comment by devworlds** [comment]
> changing things on other crates (`jd`

 oh, sure! this was changed cause when run the command cargo clippy, was asked to run a command to "solve" the warnings, so i run it, but now i know, that i do not need to change nothing outside the mining-device-sv1.

**Comment by devworlds** [comment]
its okay to open another PR, more clean?

**Comment by plebhash** [comment]
> its okay to open another PR, more clean?

you can always rebase the commit history on `devworlds:issue/migrate-sv1-mining-device-to-tracing`, which will automatically update this PR

**Comment by devworlds** [comment]
-> https://github.com/stratum-mining/stratum/pull/1309

**Pull request closed without merging**
