### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by marathon-gary**
Context: https://github.com/stratum-mining/stratum/issues/903#issuecomment-2206389058

### CODE REVIEW

**Review by plebhash — APPROVED** [review]

**Comment by plebhash** [comment]
hey @marathon-gary thanks for this contribution!

since we are updating the `CONTRIBUTING.md` file, would you mind including these as well?

https://github.com/stratum-mining/stratum/pull/1021#issuecomment-2206789002

**Comment by jbesraa** [comment]
@plebhash is the PR thing still needed after the change @Fi3 did in the branch settings?

**Comment by marathon-gary** [comment]
> @plebhash is the PR thing still needed after the change @Fi3 did in the branch settings?

Is there a branch setting that enforces code organization now?

**Comment by plebhash** [comment]
> @plebhash is the PR thing still needed after the change @Fi3 did in the branch settings?

I just rebased this PR as a test. It seems I was still included as a co-author.

> Is there a branch setting that enforces code organization now

@jbesraa  was referring to this: https://github.com/stratum-mining/stratum/pull/1030#issuecomment-2209418694

**Comment by marathon-gary** [comment]
Moved here to discuss and deduce a comprehensive solution.
https://github.com/stratum-mining/stratum/discussions/1157

**Pull request closed without merging**
