### PR TITLE
add NoDownstreamsConnected error case

### LINKED ISSUE #773: Make code more robust starting from good error management
As previously remarked, the SRI codebase should be more robust. For this reason, it may be good to improve the error management and try to avoid catch-all in pattern-matching. Here are two examples
[https://github.com/stratum-mining/stratum/blob/main/roles/pool/src/lib/status.rs#L120](https://github.com/stratum-mining/stratum/blob/main/roles/pool/src/lib/status.rs#L120)
[https://github.com/stratum-mining/stratum/blob/main/roles/pool/src/lib/mining_pool/mod.rs#L382](https://github.com/stratum-mining/stratum/blob/main/roles/pool/src/lib/mining_pool/mod.rs#L382)
The pool should never panic, in general.

Thanks to @Fi3  for pointing this out.

### PR DESCRIPTION
**Pull request by plebhash**
as described on https://github.com/stratum-mining/stratum/issues/773, the pool is being shutdown when it gets a `NoDownstreamsConnected` error.

this PR allows the pool process to continue running without crashing

### CODE REVIEW

**Comment by plebhash** [comment]
so far I introduced a new enum case into `PoolError` and made sure the `handle_error` for this case sends a `error_handling::ErrorBranch::Continue` status.

however, the pool continues to exit the process with:
```
2024-02-28T19:42:06.942250Z ERROR pool_sv2: SHUTDOWN from Downstream: Roles Logic SV2 error: `NoDownstreamsConnected`
Try to restart the downstream listener
2024-02-28T19:42:06.942268Z ERROR network_helpers::noise_connection_tokio: Disconnecting from client due to error receiving: receiving from an empty and closed channel - 127.0.0.1:60252
```

that seems to be because we are getting this `task_status` signal:
https://github.com/stratum-mining/stratum/blob/5e36e4581cd6bb153e7379e9e1c44fcfef6fdff1/roles/pool/src/main.rs#L163-L173

I know it's coming from somewhere in [`fn start()`](https://github.com/stratum-mining/stratum/blob/5e36e4581cd6bb153e7379e9e1c44fcfef6fdff1/roles/pool/src/lib/mining_pool/mod.rs#L520) but still couldn't figure out where/why.

@Fi3 any ideas?

**Comment by Fi3** [comment]
> so far I introduced a new enum case into `PoolError` and made sure the `handle_error` for this case sends a `error_handling::ErrorBranch::Continue` status.
> 
> however, the pool continues to exit the process with:
> 
> ```
> 2024-02-28T19:42:06.942250Z ERROR pool_sv2: SHUTDOWN from Downstream: Roles Logic SV2 error: `NoDownstreamsConnected`
> Try to restart the downstream listener
> 2024-02-28T19:42:06.942268Z ERROR network_helpers::noise_connection_tokio: Disconnecting from client due to error receiving: receiving from an empty and closed channel - 127.0.0.1:60252
> ```
> 
> that seems to be because we are getting this `task_status` signal:
> 
> https://github.com/stratum-mining/stratum/blob/5e36e4581cd6bb153e7379e9e1c44fcfef6fdff1/roles/pool/src/main.rs#L163-L173
> 
> I know it's coming from somewhere in [`fn start()`](https://github.com/stratum-mining/stratum/blob/5e36e4581cd6bb153e7379e9e1c44fcfef6fdff1/roles/pool/src/lib/mining_pool/mod.rs#L520) but still couldn't figure out where/why.
> 
> @Fi3 any ideas?

I wouldn't add a new variant we already have `roles_logic_sv2::Error::NoDownstreamsConnected` that cover the above case.

Why if keep failing? Because we have catch all every where in error handling. In this particular case in status.rs:

1. the function `handle_error` should do:
```rust
        PoolError::RolesLogic(roles_logic_sv2::Error::NoDownstreamsConnected) => {
            send_status(sender, e, error_handling::ErrorBranch::Continue).await
        },
```
2. the fn `send_status` when sender is `Sender::DownstreamListener` it should handle the `NoDownstreamsConnected` signaling to print an healthy message.

**Comment by plebhash** [comment]
@Fi3 I made some updates following your suggestions

**Review by GitGab19 — APPROVED** [review]
Just tested and it works as described, ACK

**Review by Fi3 — APPROVED** [review]

**Pull request merged**
