### PR TITLE
bump crates versions for docs on release v1.1.0

### LINKED ISSUE #1221: need to bump crates versions for docs on release v1.1.0
when we released `v1.1.0`, we did not bump versioning for the crates that received new Rust Docs:
- `codec_sv2`
- `const_sv2`
- `noise_sv2`

as a result, `cargo publish` failed during execution of `release-libs.yaml`.

for example, `const_sv2`:
```
Uploading const_sv2 v2.0.0 (/home/runner/work/stratum/stratum/protocols/v2/const-sv2)
error: failed to publish to registry at https://crates.io/

Caused by:
  the remote server responded with an error (status [40](https://github.com/stratum-mining/stratum/actions/runs/11365172913/job/31612774173#step:12:41)0 Bad Request): crate version `2.0.0` is already uploaded
```

this should be fixed by:
- bumping the MINOR version for these crates on the `v1.1.0` branch
- merging that back into `main`
- updating `v1.1.0` tag

### PR DESCRIPTION
**Pull request by plebhash**
close #1221

### CODE REVIEW

**Comment by Shourya742** [comment]
Semantic Versioning: `Major:Minor:Patch`.  
Can't we increase the patch number instead of the minor number?

**Comment by plebhash** [comment]
> Semantic Versioning: `Major:Minor:Patch`. Can't we increase the patch number instead of the minor number?

see https://semver.org/

> Semantic Versioning 2.0.0
> Summary
> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make incompatible API changes
> MINOR version when you add functionality in a backward compatible manner
> PATCH version when you make backward compatible bug fixes
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

we're not really fixing any bugs, and this is adding functionality in a backward compatible manner

**Comment by Shourya742** [comment]
> > Semantic Versioning: `Major:Minor:Patch`. Can't we increase the patch number instead of the minor number?
> 
> see https://semver.org/
> 
> > Semantic Versioning 2.0.0
> > Summary
> > Given a version number MAJOR.MINOR.PATCH, increment the:
> > MAJOR version when you make incompatible API changes
> > MINOR version when you add functionality in a backward compatible manner
> > PATCH version when you make backward compatible bug fixes
> > Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
> 
> we're not really fixing any bugs, and this is adding functionality in a backward compatible manner

But we're not making any changes to the code or adding any new api.

**Comment by plebhash** [comment]
> > > > Semantic Versioning: `Major:Minor:Patch`. Can't we increase the patch number instead of the minor number?
> > > 
> > > 
> > > see https://semver.org/
> > > > Semantic Versioning 2.0.0
> > > > Summary
> > > > Given a version number MAJOR.MINOR.PATCH, increment the:
> > > > MAJOR version when you make incompatible API changes
> > > > MINOR version when you add functionality in a backward compatible manner
> > > > PATCH version when you make backward compatible bug fixes
> > > > Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
> > > 
> > > 
> > > we're not really fixing any bugs, and this is adding functionality in a backward compatible manner
> > 
> > 
> > But we're not making any changes to the code or adding any new api.
> 
> if that is the case we should increase pathc version

when we first wrote Rust Docs for `framing_sv2` via #848 , we then bumped MINOR via #913

so I followed the same criteria here.

I'm fine on using this new criteria (bump PATCH instead of MINOR) for the crates we document on the next iteration.

But I don't think it would be a good idea to change this PR since those crates have now been published and that is irreversible.

**Review by GitGab19 — APPROVED** [review]
ACK

**Pull request merged**
