### PR TITLE
Use algorithm for ECDH that is described in the specification 

### PR DESCRIPTION
**Pull request by jakubtrnka**
suggestion for issue #723

### CODE REVIEW

**Comment by Sjors** [comment]
Doing this on the Bitcoin Core side requires accessing lower level libsecp functions, which might raise some review eyebrows.

**Comment by Sjors** [comment]
I would have to use `CKey::UnhashedECDH` that's introduced in https://github.com/bitcoin/bitcoin/pull/28122. That will probably slow down review by a lot.

**Comment by Fi3** [comment]
Do you think that could make sense/is possible. To modify the spec in order to avoid it?

**Comment by Sjors** [comment]
@Fi3 using EllSwift avoids this problem. Bitcoin Core has a nice high-level method for it, already used for BIP324 encryption.

**Comment by Fi3** [comment]
Ok so we can wait the decision on EllSwift. If we go with it this PR get closed otherwise we merge it

**Comment by jakubtrnka** [comment]
Generally I disagree that the specification should be modified according to the needs of a specific codebase (speaking of the bitcoin-core that @Sjors mentioned).
The concept suggested in this PR is either right or wrong: 
1. If it is right, it should be adopted because this was the core idea that makes the use of XOnlyPublicKey consistent.
2. If it is wrong, I'd like to hear and understand why.

But  let's wait for the Ellswift discussions

**Comment by Sjors** [comment]
> I disagree that the specification should be modified according to the needs of a specific codebase

That's true, but I think there is a good reason Bitcoin Core is (probably) reluctant to add this approach. It's a non-standard way of using a cryptographic function.

**Comment by lorbax** [comment]
According to what we've discussed in the [last call ](https://docs.google.com/document/d/1lkK3o-hmKeqJuHzC_GjJ778GFfQV_ObH3q6KDVgXqOE/edit#heading=h.f9ii5u3x40f4)
this solution won't be adopted. The solution with more consensus was ElligatorSwift and its ecdh procedure in libsecp256k1 and changing the specs accordingly.

**Pull request closed without merging**
