### PR TITLE
add "Project Maturity" section to `README.md`

### LINKED ISSUE #917: refine `README.md`
we should refine how we are communicating the maturity of SRI roles on `README.md`

### PR DESCRIPTION
**Pull request by plebhash**
close #917

### CODE REVIEW

**Review by pavlenex — COMMENTED** [review]
Text ACK, but should this be as h3 in the roadmap section?

**Comment by plebhash** [comment]
> Text ACK, but should this be as h3 in the roadmap section?

can you elaborate on what you mean by h3?

**Comment by pavlenex** [comment]
> > Text ACK, but should this be as h3 in the roadmap section?
> 
> 
> 
> can you elaborate on what you mean by h3?

Heading 3, 

## Roadmap
### Maturity

**Comment by plebhash** [comment]
> > > Text ACK, but should this be as h3 in the roadmap section?
> > 
> > 
> > can you elaborate on what you mean by h3?
> 
> Heading 3,
> 
> ## Roadmap
> ### Maturity

done

**Review by pavlenex — APPROVED** [review]

**Pull request merged**
