### PR TITLE
V1 Bug Fix: Match Case Ordering of mining.subscribe

### PR DESCRIPTION
**Pull request by coleFD**
closes https://github.com/stratum-mining/stratum/issues/365.

Note: there is an open question on the linked issue asking if this needs to be considered in other array match cases in V1

### CODE REVIEW

**Comment by Fi3** [comment]
Hi, I think that the issue is in how the message is encoded, (here https://github.com/stratum-mining/stratum/blob/main/protocols/v1/src/methods/server_to_client.rs#L376) not how is decoded. That cause the translator work with both S9 and cpuminer, so is more likely that the bug is in the examples/sv1-mining-device.

**Comment by coleFD** [comment]
> Hi, I think that the issue is in how the message is encoded, (here https://github.com/stratum-mining/stratum/blob/main/protocols/v1/src/methods/server_to_client.rs#L376) not how is decoded. That cause the translator work with both S9 and cpuminer, so is more likely that the bug is in the examples/sv1-mining-device.



> Hi, I think that the issue is in how the message is encoded, (here https://github.com/stratum-mining/stratum/blob/main/protocols/v1/src/methods/server_to_client.rs#L376) not how is decoded. That cause the translator work with both S9 and cpuminer, so is more likely that the bug is in the examples/sv1-mining-device.

@Fi3 I closed the PR but ran into this https://en.bitcoin.it/wiki/Stratum_mining_protocol#mining.subscribe. Not sure if this is a good source, but is there the possibility that miners could handle either case?

**Comment by Fi3** [comment]
yep we should dig more into it. Also we can not have a value serialized in way and de serialized in another way so we have to change something

**Comment by Fi3** [comment]
Ok sorry disregard what I my first message, is no sense. The part used by the translator is line 376 and is the working one.
The part used by the examples/sv1-mining-device is the one that you changed and is the not working one.

So I reopen it. But before merging it we need to change the variable names at line 389.

**Comment by Fi3** [comment]
this names:
```rust
        let (extra_nonce1, extra_nonce2_size, subscriptions_) = match &params[..] {
 ```
 are not what you are mathcing against they should be
 ```rust
         let (subscriptions_, extra_nonce1, extra_nonce2_size) = match &params[..] {
```

**Review by rrybarczyk — APPROVED** [review]

**Pull request merged**
