### PR TITLE
FFI: pass in `message` to `Sv2Error::PayloadTooBig` variant

### PR DESCRIPTION
**Pull request by plebhash**
close https://github.com/stratum-mining/stratum/issues/166

in this PR we are making `Sv2Error::PayloadTooBig` into `Sv2Error::PayloadTooBig(*const std::ffi::c_char)` so that it can carry `message`.

as @rrybarczyk put it on the original issue description:
> This will help tremendously with better understanding error messages for the sv2 bindings.

---

Note 1: this PR is not doing `Sv2Error::PayloadTooBig(String)` like it was suggested on the original issue description.

`*const std::ffi::c_char` was chosen instead of `String` for easier `cbindgen` compatibility. If `String` is used, `sv2.h` has incomplete type ‘String’ and compilation of `examples/interop-cpp/template-provider/template-provider.cpp` breaks as a consequence.

---

Note 2: this PR is not modifying `trait Frame` like it was suggested on the original issue description.

Instead, we simply implement the `Display` trait for `Sv2Message` and the error can be created via:
```rust
let message: Sv2Message;
...
Sv2Error::PayloadTooBig(
  CString::new(format!("{}", message))
    .expect("CString::new failed")
    .into_raw(),
))
```

### CODE REVIEW

**Comment by plebhash** [comment]
@Fi3 is this useful? I wrote this PR just as an exercise to help me explore `sv2-ffi`. But I can also close it if you feel it's not relevant.

**Comment by Fi3** [comment]
A lot of time that I do not work on that part. Btw we should have a safer (respect to c_char) CVec. Maybe we can use it instead, not sure btw. Have you looked into it? Also remember to update the c headers with ./build-header.sh and to put them on the sv2ffi crate.

**Comment by plebhash** [comment]
> Btw we should have a safer (respect to c_char) CVec. Maybe we can use it instead, not sure btw. Have you looked into it?

I saw `CVec` on some parts of the code but didn't consider it for replacing `String`. I will look into it 👍

> Also remember to update the c headers with ./build-header.sh and to put them on the sv2ffi crate.

yes, I am taking care of that 👍

**Comment by Fi3** [comment]
take a look also here:

https://github.com/stratum-mining/stratum/tree/dev/examples/interop-cpp#cvec

**Comment by plebhash** [comment]
@Fi3 replace `*const c_char` with `CVec` here https://github.com/stratum-mining/stratum/pull/679/commits/96878eaed7d4235f8709492fc95bcb7b8d5d973d

**Pull request merged**
