### PR TITLE
MG understands `SubmitSolution` as a valid JD message

### LINKED ISSUE #1002: MG doesn't understand `SubmitSolution` as a valid JD message
as described in https://github.com/stratum-mining/stratum/issues/912#issuecomment-2187118010, Message Generator is not able to parse a `SubmitSolution` if it is declared under the `job_declaration_messages` JSON field of the test.

```
STD ERR: called `Result::unwrap()` on an `Err` value: Error("unknown variant `SubmitSolution`, expected one of `AllocateMiningJobTokenSuccess`, `AllocateMiningJobToken`, `DeclareMiningJob`, `DeclareMiningJobSuccess`, `DeclareMiningJobError`, `IdentifyTransactions`, `IdentifyTransactionsSuccess`, `ProvideMissingTransactions`, `ProvideMissingTransactionsSuccess`", line: 36, column: 32)
```

### PR DESCRIPTION
**Pull request by plebhash**
close #1002

### CODE REVIEW

**Comment by lorbax** [comment]
It appears to me that you are sending a `SubmitSolution` right after receiving `SetupConnectionSuccess`.
What you miss IMO
mock --> JDS: AllocateMiningJobToken
mock <-- JDS: AllocateMiningJobToken.success
mock --> JDS: DeclareMiningJob
mock <-- JDS: DeclareMiningJob.success

The submitted solution should contain the transactions of DeclareMiningJob, so you have to take a real. Also, to check that JDS submit solution works, you have to to prevent submit solution from JDC (by patching the JDC not doing so), and clearly the JDS connected to a bitcoin node. There is also the possibility to use your signet, mine some non empty blocks and use those blocks for the purpose.

What you are trying to do is tricky, ping me if you need help

**Comment by plebhash** [comment]
> What you miss IMO
mock --> JDS: AllocateMiningJobToken
mock <-- JDS: AllocateMiningJobToken.success
mock --> JDS: DeclareMiningJob
mock <-- JDS: DeclareMiningJob.success

I found #1002 while working on #912, and while working there I did follow the message flow indicated above. But the MG behavior that I'm describing on #1002 happens independently of these messages are not related to it.

So I intentionally left these messages out of the flow. We just need an atomic way to get MG to parse a `SubmitSolution`, and this test was the smallest possible test to achieve this.

The messages listed above should be ignored on the context of this issue.

**Comment by plebhash** [comment]
todo: try with https://github.com/stratum-mining/stratum/pull/949

**Comment by plebhash** [comment]
> todo: try with #949

@lorbax I tried merging your changes from `MG-fix-primitives-serialization-and-unit-tests` and the issue persists.

**Comment by plebhash** [comment]
hey @lorbax just FYI

I found the root cause of the problems discussed above, I described it on https://github.com/stratum-mining/stratum/issues/1018

once https://github.com/stratum-mining/stratum/issues/1019 is merged, I will make this PR ready for review

**Review by GitGab19 — APPROVED** [review]

**Pull request merged**
