### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by rrybarczyk**
- Adds dual license: MIT + Apache 2.0
- Requires approval from all individuals who have previously committed to the repo

### CODE REVIEW

**Comment by Kodylow** [comment]
ACK

**Comment by ccdle12** [comment]
ACK

**Comment by rrybarczyk** [comment]
@Eunoia1729 and @louneskmt, will you to approve the use of the dual MIT + Apache 2.0 license by leaving an ACK comment indicating your approval?

**Comment by rrybarczyk** [comment]
ACK

**Comment by Eunoia1729** [comment]
ACK

**Comment by pavlenex** [comment]
It seems to be that all contributors have given their permission for dual licensing. I think @Fi3 is the only one left to ACK.

**Comment by Fi3** [comment]
ACK

**Pull request merged**
