### PR TITLE
Limit acceptable line length to avoid DoS (using tokio)

### PR DESCRIPTION
**Pull request by douglaz**
Fixes https://github.com/stratum-mining/stratum/issues/429
(Alternative to https://github.com/stratum-mining/stratum/pull/497)

Open questions:
1) What `MAX_LINE_LENGTH` should be?
2) Should we also use `FramedRead/LinesCodec` in other places, like in examples?

### CODE REVIEW

**Comment by coleFD** [comment]
> Fixes #429 (Alternative to #497)
> 
> Open questions:
> 
> 1. What `MAX_LINE_LENGTH` should be?
> 2. Should we also use `FramedRead/LinesCodec` in other places, like in examples?

@fi3 would the pool downstream reader benefit from this? Not sure if its worth the time putting this in the examples?

**Comment by douglaz** [comment]
Flaky test?

**Comment by coleFD** [comment]
> Flaky test?

yep

**Review by coleFD — APPROVED** [review]

**Comment by pavlenex** [comment]
Hey @douglaz could you rebase please?

**Comment by pavlenex** [comment]
Closing in favour of https://github.com/stratum-mining/stratum/pull/748

**Pull request closed without merging**
