### PR TITLE
fix: Rm 3rd party hex crate dependency 

### PR DESCRIPTION
**Pull request by star-gazer111**
fixes [375](https://github.com/stratum-mining/stratum/issues/375)

### CODE REVIEW

**Comment by Fi3** [comment]
this code do not compile

**Comment by star-gazer111** [comment]
Oh I see, am I making some basic mistake here?

**Comment by Fi3** [comment]
have you tried to build the code before pushing it? what is the output of cargo build?

**Comment by star-gazer111** [comment]
It is throwing me the following error : 
`error: failed to select a version for the requirement `hex-conservative = "^0.4.3"`
candidate versions found which didn't match: 0.2.0, 0.1.1, 0.1.0, ...
location searched: crates.io index
required by package `sv1_api v1.0.0 (/home/vasuk/stratum/protocols/v1)`
perhaps a crate was updated and forgotten to be re-vendored? `

If I change the version of hex-conservative in cargo.toml from 0.4.3 to 0.2.0 it gives me a very obvious error as follows:
`error[E0433]: failed to resolve: use of undeclared crate or module 'hex',  ^^^ use of undeclared crate or module 'hex'`

**Comment by plebhash** [comment]
@star-gazer111 this task is not about simply replacing the dependency on the `Cargo.toml`

you also need to adapt the internal logic inside the code so that it uses the new dependency

that implies understanding how `hex` was used previously and how `hex-conservative` can be used as a replacement

**Comment by star-gazer111** [comment]
got it, on to it!

**Comment by star-gazer111** [comment]
just deleted the fork because of merge conflicts in #837 so the pr is closed for now, I'm working on it and almost done with the part of shifting the logic from `hex` to `hex-conservative` and will open a new pr in the next couple of days.

**Pull request closed without merging**
