### PR TITLE
Added docs around starting up the various roles

### PR DESCRIPTION
**Pull request by darricksee**
This fills the gap needed by new users on how to properly setup 2 of easiest configurations to get started.

### CODE REVIEW

**Comment by xraid** [comment]
Readable ++

 i have not tested here yet but would like further explanation of mentioned in config `tp_address = "75.119.150.111:8442"` 

where is code for that tp_address = "75.119.150.111:8442"` and documentation for build and run ?

it is the template-provider with a patched bitcoind i assume but would like doc make clear

**Comment by pavlenex** [comment]
If I'm not mistaken, the template provider code that's hosted is here https://github.com/stratum-mining/stratum/pull/409
As for instructions on how to build & run @ccdle12 may be able to point you out.

**Comment by xraid** [comment]
last commit for *POCRegtest-2-0-0* is on Sep 9, 2022 ?

would be great to add to this doc how to run the patched *bitcoind* that i assume is  *tp_address = "75.119.150.111:8442"*

or doeas  *tp_address = "75.119.150.111:8442"* have *JobNegotiator* running as well ?

**Comment by darricksee** [comment]
No JN at this point. It's just the patched bitcoind. @Fi3 would have to comment on what version/branch this is though.

> last commit for _POCRegtest-2-0-0_ is on Sep 9, 2022 ?
> 
> would be great to add to this doc how to run the patched _bitcoind_ that i assume is _tp_address = "75.119.150.111:8442"_
> 
> and does _tp_address = "75.119.150.111:8442"_ have a running _JobNegotiator_ also ?

**Comment by darricksee** [comment]
> 

Updated

**Pull request merged**
