### PR TITLE
Closes #784

### LINKED ISSUE #784: small bugs in the JDS mempool
Here
[https://github.com/stratum-mining/stratum/blob/main/roles/jd-server/src/lib/mempool/mod.rs#L85](https://github.com/stratum-mining/stratum/blob/main/roles/jd-server/src/lib/mempool/mod.rs#L85)
there is a tokio task that is awaited, which does not make any sense. Since the function `update_mempool` is already an async method, I think that the generation of a new task can be definitely can be avoided without any substantial work.

Also the rpc method `get_raw_mempool_verbose` should be renamed with `get_raw_mempool`, as at the end the rpc call is `getrawmempool` without verbose.

good for first issue!

### PR DESCRIPTION
**Pull request by NonsoAmadi10**
### What does this PR do?

Refractor update_mempool module in JDS mempool module for simplified async flow

- Removed the unnecessary use of tokio::task::spawn in update_mempool, leveraging the existing async function context for all operations.
- Renamed get_raw_mempool_verbose to get_raw_mempool to align with the underlying RPC call.
- Streamlined error handling by removing .map_err(JdsMempoolError::TokioJoin) since separate async task spawning is no longer used.
- Simplified control flow with direct return statements for error cases and inline error handling for lock operations.

### CODE REVIEW

**Comment by NonsoAmadi10** [comment]
Hi @pavlenex i think i might need help with passing the MG test. I have been able to fix everything else but this one seems like a constant fail for me. I appreciate your insight in advance

**Comment by pavlenex** [comment]
I think @GitGab19 and @lorbax should know better, it seems it's configuration problem `bad-pool-config-test.json` @GitGab19 does this mean the pool was down when the test was run, I'll re run it.

**Comment by NonsoAmadi10** [comment]
I think it is still failing. I don't know if it is something I am missing on my part

**Comment by pavlenex** [comment]
Afair this test is flaky. Let's see what experts have to say. For now I can only post logs

```
STD ERR:    Compiling pool_sv2 v0.1.0 (/home/runner/work/stratum/stratum/roles/pool)
STD ERR:     Finished dev [optimized + debuginfo] target(s) in 1m 23s
STD ERR:      Running `target/llvm-cov-target/debug/pool_sv2 -c ../test/config/pool-mock-tp-bad-coinbase.toml`
STD OUT: 2024-03-11T17:51:32.642362Z  INFO pool_sv2: Pool INITIALIZING with config: "../test/config/pool-mock-tp-bad-coinbase.toml"
STD OUT: 2024-03-11T17:51:32.642393Z ERROR pool_sv2: Failed to get coinbase output: InvalidOutputScript
STD ERR: info: cargo-llvm-cov currently setting cfg(coverage); you can opt-out it by passing --no-cfg-coverage
STD ERR:     Finished dev [optimized + debuginfo] target(s) in 0.11s
STD ERR:      Running `target/llvm-cov-target/debug/pool_sv2 -h -c ../test/config/pool-mock-tp.toml`
STD OUT: 2024-03-11T17:51:32.983701Z ERROR pool_sv2: Usage: -h/--help, -c/--config <path|default pool-config.toml>
STD ERR: info: cargo-llvm-cov currently setting cfg(coverage); you can opt-out it by passing --no-cfg-coverage
STD ERR:     Finished dev [optimized + debuginfo] target(s) in 0.10s
STD ERR:      Running `target/llvm-cov-target/debug/pool_sv2 -c ../test/config/pool-mock-tp-bad-config.toml`
STD OUT: 2024-03-11T17:51:33.317829Z ERROR pool_sv2: Failed to parse config: missing field `listen_address` at line 1 column 1
STD ERR: info: cargo-llvm-cov currently setting cfg(coverage); you can opt-out it by passing --no-cfg-coverage
STD ERR:     Finished dev [optimized + debuginfo] target(s) in 0.11s
STD ERR:      Running `target/llvm-cov-target/debug/pool_sv2 -c ../test/config/no-config-at-this-path.toml`
STD OUT: 2024-03-11T17:51:33.655205Z ERROR pool_sv2: Failed to read config: No such file or directory (os error 2)
STD ERR: info: cargo-llvm-cov currently setting cfg(coverage); you can opt-out it by passing --no-cfg-coverage
STD ERR:     Finished dev [optimized + debuginfo] target(s) in 0.11s
STD ERR:      Running `target/llvm-cov-target/debug/pool_sv2 -c ../test/config/pool-mock-tp.toml`
STD OUT: 2024-03-11T17:51:33.987445Z  INFO pool_sv2: Pool INITIALIZING with config: "../test/config/pool-mock-tp.toml"
STD OUT: 2024-03-11T17:51:33.988181Z  INFO pool_sv2::lib::template_receiver: Connected to template distribution server at 127.0.0.1:8442
STD OUT: 2024-03-11T17:51:33.988718Z DEBUG network_helpers::noise_connection_tokio: Initializing as downstream for - 127.0.0.1:8442
STD OUT: Initializing as upstream for - 127.0.0.1:38228
STD OUT: Noise handshake complete - 127.0.0.1:38228
STD OUT: 2024-03-11T17:51:33.995967Z DEBUG 
```

**Comment by GitGab19** [comment]
> I think @GitGab19 and @lorbax should know better, it seems it's configuration problem `bad-pool-config-test.json` @GitGab19 does this mean the pool was down when the test was run, I'll re run it.

Everything is up and running on our VPS.
Sometimes MG tests simply fail, I couldn't find a specific reason for that

**Comment by GitGab19** [comment]
I would wait for @lorbax addiction to PR #772 btw, since it will likely change something in the part touched by this PR

**Comment by GitGab19** [comment]
@NonsoAmadi10 could you rebase this PR?
I guess something has been changed after yesterday release, and I see conflicts here

**Comment by NonsoAmadi10** [comment]
> @NonsoAmadi10 could you rebase this PR? I guess something has been changed after yesterday release, and I see conflicts here

Alright, let me do that now

**Comment by NonsoAmadi10** [comment]
I would be closing this PR because I don't want to force push and reimplementing this again. Thanks

**Pull request closed without merging**
